### ISSUE TITLE
Bower dependency ?

### ISSUE THREAD

**Issue by emudojo** [atomictag/incremental-bars#5]
I tried to install this on an existing project and got this error, Incremental-bars itself has no dependencies on bower not sure on the other packages it includes.

npm install incremental-bars --save

+-- UNMET PEER DEPENDENCY bower@1.7.2
`-- incremental-bars@1.0.6

npm WARN grunt-bower-requirejs@0.4.4 requires a peer of bower@~0.x but none was installed.
npm WARN qfloor-webapp@0.0.1 No description
npm WARN qfloor-webapp@0.0.1 No repository field.
npm WARN qfloor-webapp@0.0.1 No license field.

I don´t see why it also forces me to install webpack (we use grunt)

**Comment by atomictag** [comment]
Pretty weird. This is what I see after a clean npm install:

└─┬ incremental-bars@1.0.6
  ├─┬ handlebars@4.0.10
  │ └── uglify-js@2.8.29
  ├─┬ html-minifier@3.5.2
  │ ├── clean-css@4.1.5
  │ └── uglify-js@3.0.23
  └─┬ htmlparser2@3.9.2
    └─┬ readable-stream@2.3.3
      ├── safe-buffer@5.1.1
      └── string_decoder@1.0.3

**Comment by emudojo** [comment]
NVM it was an old package that is broken, nothing related. I need to update the project away from requireJS ... damn

please Close

**Comment by rafde** [comment]
@emudojo use webpack. It works with requirejs module syntax.
