### ISSUE TITLE
attribute innerhtml does not work on second patch

### ISSUE THREAD

**Issue by JSteunou** [atomictag/incremental-bars#6]
Hi,

I have some content to render as html (yes, I know, bad, booo) but shits happen. I tried with a handlebars helper, it's very complicated but work, then I find some documentation about `innerhtml` idom attribute. It works the first time, but consecutive render / patch erase the content.

**Comment by JSteunou** [comment]
My bad, I totally forget that *I actually addded* this attribute logic as an idom helper :(

**Comment by JSteunou** [comment]
My bad, I totally forget that *I actually addded* this attribute logic as an idom helper :(

**Comment by JSteunou** [comment]
But still, maybe you can enlight me:

```js
import {attributes, skip} from 'incremental-dom';

attributes.innerhtml = function(el, property, value) {
    if (el.__innerHTML !== value) {
        el.__innerHTML = value;
        el.innerHTML = value;
    }
    skip();
};
```

I did a thing like this, but `innerhtml` is called only at first render, not on patch

**Comment by atomictag** [comment]
Yeh that's because Incremental Dom does not see any change in the element and therefore does nothing after the first patch. Not sure if it helps but I use a helper:

    Handlebars.registerHelper('innerHtml', function(string, options) {
        var backend = options.data && options.data.backend;
        if(backend === 'idom') {
            if(string instanceof Handlebars.SafeString) {
                string = string.string;
            }
            $(IncrementalDOM.currentElement()).empty().append($(string));
            IncrementalDOM.skip();
        } else {
            return string;
        }
    })

and then in my template:
  
    {{ innerHtml '<div>I am a div</div>' }}

**Comment by JSteunou** [comment]
Yeah, I did that too, but I though it could be much cooler with the idom attribute super powa instead. Also it would open new feature above handlebars helpers.

I'm still curious, iDom does not see any change, ok, but why it removes the content? I'm not expecting it calling the function at each patch, but at least keep the content :/

**Comment by JSteunou** [comment]
I did update the comment above, was so incomprehensible

**Comment by atomictag** [comment]
During the second patch innerHtml is not called and therefore skip() is not called either. Therefore iDOM sees "alien" elements and gets rid of them.

**Comment by JSteunou** [comment]
Is there a way to force the call to `innerhtml` or to force a skip() on the second patch?

**Comment by atomictag** [comment]
Not sure. Something to try would be to wrap your innerhtml attribute in a HB block like this:

    <div ... {{#if 1}}innerhtml="..."{{/if}} ...>

which would force (in incremental-bars) the attribute to be set with `attr` rather than by `elementOpen`. Also the following produces the same result and it's a bit cleaner:

    <div ... innerhtml="{{ myContextVar }}" ...>

**Comment by atomictag** [comment]
Another thing that you can try (I am still assuming you are using `incremental-bars` of course, with its default options) is to add the attribute `data-partial-id`to your element

    <div ... innerhtml="..." data-partial-id="whatever" ...>

which generates a `skip()` for you

**Comment by JSteunou** [comment]
I already try the 1st example without success, and the second throw an error

```
Uncaught Error: skip() must come before any child declarations inside the current element.
    at assertNoChildrenDeclaredYet (VM801 incremental-dom-cjs.js:457)
    at skip (VM801 incremental-dom-cjs.js:995)
    at Object.main (VM880 body.hbs:20)
    at main (VM797 runtime.js:175)
    at ret (VM797 runtime.js:178)
    at eval (VM801 incremental-dom-cjs.js:703)
    at f (VM801 incremental-dom-cjs.js:667)
    at child.exports.default [as _renderHtml] (VM876 idom.js:11)```

**Comment by atomictag** [comment]
I don't use the cjs version of icremental dom so `assertNoChildrenDeclaredYet` is new to me. The non-cjs version of incremental-dom seems to have a different implementation for `skip` and no assertion.

**Comment by JSteunou** [comment]
Hooo I'll try that

**Comment by JSteunou** [comment]
That works very well!

To sum up for those having the same trouble:

1. force webpack to use `'incremental-dom/dist/incremental-dom'` through alias
2. add the special skip node attribute (`data-partial-id` by default) to trigger a skip for consecutive render

and you are all set, idom custom attribute works :)

**Comment by JSteunou** [comment]
but now I'm confused about why the cjs build is different from the *normal* build oO
